### ISSUE TITLE
bug: wrong keydown event logic

### ISSUE THREAD

**Issue by avoylenko** [jambonz/chrome-extension-dialer#23]
The `keydown` event triggers the dmtf playback everywhere in the UI even your are not in a call.

**Comment by xquanluu** [comment]
Hi @avoylenko 
So you would not like to have input number from keyboard,
The input from keyboard should be used for DTMF only?

**Comment by avoylenko** [comment]
From my point of view the DTMF playback should be active only if you have an ongoing call session(or you are entering the phone number to make an outgoing call) and should be disabled if you navigated away from the phone view.

**Comment by xquanluu** [comment]
oh I see what you means now,

**Comment by avoylenko** [comment]
solved
